# Generated by Django 5.2.12 on 2026-04-05 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
        ('land', '0001_initial'),
        ('vehicle', '0001_initial'),
        ('worklog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expense_date', models.DateField(db_index=True)),
                ('expense_type', models.CharField(choices=[('wage', 'Wage'), ('transport', 'Transport'), ('fuel', 'Fuel'), ('lease', 'Lease'), ('maintenance', 'Maintenance'), ('other', 'Other')], db_index=True, max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='employee.employee')),
                ('land', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='land.land')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='vehicle.vehicle')),
                ('worklog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='worklog.worklog')),
            ],
            options={
                'ordering': ['-expense_date', '-created_at'],
                'indexes': [models.Index(fields=['expense_date', 'expense_type'], name='expenses_ex_expense_90b558_idx')],
            },
        ),
    ]
