# Generated by Django 5.2.12 on 2026-04-05 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee_code', models.CharField(max_length=40, unique=True)),
                ('full_name', models.CharField(db_index=True, max_length=180)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('supervisor', 'Supervisor'), ('worker', 'Worker')], db_index=True, default='worker', max_length=20)),
                ('department', models.CharField(db_index=True, max_length=120)),
                ('designation', models.CharField(blank=True, max_length=120)),
                ('phone_number', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('daily_wage', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('joined_on', models.DateField()),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['full_name'],
                'indexes': [models.Index(fields=['department', 'role'], name='employee_em_departm_1b10f6_idx'), models.Index(fields=['employee_code', 'is_active'], name='employee_em_employe_3c3609_idx')],
            },
        ),
    ]
