# Generated by Django 5.2.12 on 2026-04-05 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registration_number', models.CharField(max_length=40, unique=True)),
                ('vehicle_type', models.CharField(db_index=True, max_length=80)),
                ('capacity', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('driver_name', models.CharField(blank=True, max_length=180)),
                ('driver_phone', models.CharField(blank=True, max_length=30)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['registration_number'],
            },
        ),
        migrations.CreateModel(
            name='VehicleUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usage_date', models.DateField(db_index=True)),
                ('source', models.CharField(blank=True, max_length=180)),
                ('destination', models.CharField(blank=True, max_length=180)),
                ('start_odometer', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True)),
                ('end_odometer', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True)),
                ('fuel_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to='vehicle.vehicle')),
            ],
            options={
                'ordering': ['-usage_date', '-created_at'],
                'indexes': [models.Index(fields=['usage_date', 'vehicle'], name='vehicle_veh_usage_d_5bc1c3_idx')],
            },
        ),
    ]
