# Generated by Django 5.2.12 on 2026-04-05 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
        ('land', '0001_initial'),
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('work_date', models.DateField(db_index=True)),
                ('coconut_count', models.PositiveIntegerField(default=0)),
                ('bag_count', models.PositiveIntegerField(default=0)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('photo_proof', models.ImageField(blank=True, null=True, upload_to='worklog-proofs/')),
                ('notes', models.TextField(blank=True)),
                ('land', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='worklogs', to='land.land')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_worklogs', to='employee.employee')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worklogs', to='vehicle.vehicle')),
            ],
            options={
                'ordering': ['-work_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkLogAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task_role', models.CharField(blank=True, max_length=80)),
                ('units_completed', models.PositiveIntegerField(default=0)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worklog_assignments', to='employee.employee')),
                ('worklog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='worklog.worklog')),
            ],
            options={
                'ordering': ['employee__full_name'],
            },
        ),
        migrations.AddIndex(
            model_name='worklog',
            index=models.Index(fields=['work_date', 'land'], name='worklog_wor_work_da_3e766c_idx'),
        ),
        migrations.AddConstraint(
            model_name='worklogassignment',
            constraint=models.UniqueConstraint(fields=('worklog', 'employee'), name='unique_worklog_employee'),
        ),
    ]
