# Generated by Django 5.2.12 on 2026-04-05 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LandOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=180)),
                ('phone_number', models.CharField(blank=True, max_length=30)),
                ('village', models.CharField(blank=True, db_index=True, max_length=120)),
                ('address', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Land',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=180)),
                ('village', models.CharField(db_index=True, max_length=120)),
                ('area_acres', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('lease_start_date', models.DateField()),
                ('lease_end_date', models.DateField()),
                ('lease_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tree_count', models.PositiveIntegerField(default=0)),
                ('lease_notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lands', to='land.landowner')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['village', 'is_active'], name='land_land_village_33822b_idx'), models.Index(fields=['lease_start_date', 'lease_end_date'], name='land_land_lease_s_673322_idx')],
            },
        ),
    ]
