# Generated by Django 5.2.13 on 2026-04-26 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='land',
            name='agreed_emi_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount to be paid per installment', max_digits=12),
        ),
        migrations.CreateModel(
            name='LandLeasePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_type', models.CharField(choices=[('advance', 'Advance'), ('emi', 'EMI Installment'), ('other', 'Other')], default='emi', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('land', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='land.land')),
            ],
            options={
                'ordering': ['-payment_date', '-created_at'],
                'indexes': [models.Index(fields=['land', 'payment_date'], name='land_landle_land_id_857230_idx')],
            },
        ),
    ]
